server:
  port: 8761
spring:
  main:
    banner-mode: off
  application:
    name: discovery-service
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 90
logging:
  level:
    org.springframework.cloud.netflix.eureka: debug